###############################################
###############################################
###############################################
#### This file has simple wrappers to PyQt5 ####
###############################################
###############################################
###############################################



from PyQt5 import QtGui,QtWidgets  # Import the PyQt5 module we'll need
from PyQt5.QtGui import QPixmap
#from PyQt5.QtCore import Signal
import sys  # We need sys so that we can pass argv to QApplication
import numpy as np
import os

# This file holds our MainWindow and all interface related things
import interface # this file is generated by Qt-designer 

QtGui = QtWidgets
app = QtWidgets.QApplication(sys.argv)  # A new instance of QApplication





def show_error(message,title="Error"):
    """Report an error in the GUI, not only on a terminal nobody may see"""
    print(title+": "+message)
    try:
        QtWidgets.QMessageBox.critical(None,title,message)
    except Exception: # never let the reporting itself break the callback
        pass


def show_warning(message,title="Warning"):
    """Report a non-fatal problem in the GUI"""
    print(title+": "+message)
    try: QtWidgets.QMessageBox.warning(None,title,message)
    except Exception: pass


def show_info(message,title="Tranci"):
    """Report a result in the GUI"""
    print(title+": "+message)
    try: QtWidgets.QMessageBox.information(None,title,message)
    except Exception: pass


def status(message,timeout=0):
    """Show a message in the status bar of the main window"""
    print(message)
    try:
        form.statusbar.showMessage(message,timeout)
        app.processEvents() # paint it now, the callback may take long
    except Exception: pass


def get_failsafe(f,robust=True):
    """Return a function that if fails things do not break down"""
    def fout():
        if not robust: return f()
        try: return f()
        except Exception as e:
            import traceback
            traceback.print_exc()
            # PyQt aborts the whole process on an exception escaping a slot,
            # so everything reaching a button must be caught here
            show_error("%s: %s"%(type(e).__name__,e))
            return None
    return fout



class App(QtGui.QMainWindow, interface.Ui_MainWindow):
    def __init__(self):
        super(self.__class__, self).__init__()
        self.setupUi(self)  # This is defined in interface.py file automatically
        # It sets up layout and widgets that are defined
    def run(self):
      self.show()  # Show the form
      app.exec_()  # and execute the app
    def connect_clicks(self,ds0):
      """Connect the different functions"""
      ds = dict()
      for d in ds0: ds[d] = get_failsafe(ds0[d],robust=True)
      for d in ds:
          bu = getattr(self,d) # label in the interface
          fun = ds[d] # function to call
          if hasattr(bu,"clicked"): bu.clicked.connect(fun) # button
          else: bu.triggered.connect(fun) # menu action


def main():
    global form
    form = App()  # We set the form to be our ExampleApp (interface)
    return form


def add_numeric_validators(names):
  """Attach a numeric validator to the given QLineEdit widgets

  interface.ui ships no validators, so the fields accept anything; a locale
  decimal comma or a stray unit used to become a silent zero.
  """
  from PyQt5.QtGui import QDoubleValidator
  from PyQt5.QtCore import QLocale
  val = QDoubleValidator()
  val.setNotation(QDoubleValidator.ScientificNotation)
  val.setLocale(QLocale(QLocale.C)) # a dot is the decimal separator
  for name in names:
    obj = getattr(form,name,None)
    if obj is None: continue # widget not in this interface
    try: obj.setValidator(val)
    except AttributeError: pass # not a QLineEdit


def get(name,string=False):
  try:
    obj = getattr(form,name) # get the object
  except AttributeError: # a genuinely missing widget keeps the old behaviour
    print(name,"not found, set to zero")
    return 0
  if hasattr(obj,"value"): # QSpinBox, already validated by the widget
    out = obj.value()
    print(name,out)
    return str(out) if string else out
  out = obj.text()
  print(name,out)
  if string: return out # return as string
  try:
    return float(out) # return as float
  except (TypeError,ValueError):
    # do not silently zero a parameter: that changes the physics with no trace
    raise ValueError("The field '%s' does not contain a valid number: '%s'"
                     %(name,out))



def getbox(name):
  try:
    obj = getattr(form,name) # get the object
    return str(obj.currentText()) # return the text
  except:
    print(name,"not found, set to empty string")
    return 0



def set_value(name,text):
  obj = getattr(form,name) # get the object
  if hasattr(obj,"setValue"): obj.setValue(int(text)) # QSpinBox
  else: obj.setText(str(text)) # QLineEdit
  app.processEvents() # update the interface

modify = set_value # old name


INPUT_TYPES = (QtWidgets.QLineEdit,QtWidgets.QSpinBox,QtWidgets.QComboBox,
               QtWidgets.QCheckBox) # widgets that hold user parameters


def input_widgets():
  """Return {name: widget} for every parameter field of the interface"""
  out = dict()
  for w in form.centralwidget.findChildren(INPUT_TYPES):
    name = w.objectName()
    if name.startswith("qt_"): continue # internal children of a spinbox
    out[name] = w
  return out


def get_all_inputs():
  """Return every parameter field of the interface as {name: value}"""
  out = dict()
  for name,w in input_widgets().items():
    if isinstance(w,QtWidgets.QSpinBox): out[name] = w.value()
    elif isinstance(w,QtWidgets.QComboBox): out[name] = w.currentText()
    elif isinstance(w,QtWidgets.QCheckBox): out[name] = w.isChecked()
    else: out[name] = w.text()
  return out


def set_all_inputs(d):
  """Fill the parameter fields from a dictionary, return the unknown keys"""
  ws = input_widgets()
  unknown = []
  for name,v in d.items():
    w = ws.get(name,None)
    if w is None: unknown.append(name) ; continue
    if isinstance(w,QtWidgets.QSpinBox): w.setValue(int(v))
    elif isinstance(w,QtWidgets.QComboBox):
      i = w.findText(str(v))
      if i<0: unknown.append(name+"="+str(v)) # option no longer offered
      else: w.setCurrentIndex(i)
    elif isinstance(w,QtWidgets.QCheckBox): w.setChecked(bool(v))
    else: w.setText(str(v))
  app.processEvents() # update the interface
  return unknown


def is_checked(name):
  obj = getattr(form,name) # get the object
  return obj.isChecked()



def set_image(name,path):
  """Set a certain image"""
  label = getattr(form,name) # get the object
  pixmap = QPixmap(path)
  label.setPixmap(pixmap)
  label.show()


def set_logo(name,path):
  """Set a certain logo"""
  set_image(name,path)
  




if __name__ == '__main__':  # if we're running file directly and not importing it
    main()  # run the main function



