###############################################
###############################################
###############################################
#### This file has simple wrappers to qt4  ####
###############################################
###############################################
###############################################



from PyQt5 import QtGui,QtWidgets  # Import the PyQt5 module we'll need
from PyQt5.QtGui import QPixmap
#from PyQt5.QtCore import Signal
import sys  # We need sys so that we can pass argv to QApplication
import numpy as np
import os

# This file holds our MainWindow and all interface related things
import interface # this file is generated by Qt-designer 

QtGui = QtWidgets
app = QtWidgets.QApplication(sys.argv)  # A new instance of QApplication





def show_error(message,title="Error"):
    """Report an error in the GUI, not only on a terminal nobody may see"""
    print(title+": "+message)
    try:
        QtWidgets.QMessageBox.critical(None,title,message)
    except Exception: # never let the reporting itself break the callback
        pass


def get_failsafe(f,robust=True):
    """Return a function that if fails things do not break down"""
    def fout():
        if not robust: return f()
        try: return f()
        except Exception as e:
            import traceback
            traceback.print_exc()
            # PyQt aborts the whole process on an exception escaping a slot,
            # so everything reaching a button must be caught here
            show_error("%s: %s"%(type(e).__name__,e))
            return None
    return fout



class App(QtGui.QMainWindow, interface.Ui_MainWindow):
    def __init__(self):
        super(self.__class__, self).__init__()
        self.setupUi(self)  # This is defined in interface.py file automatically
        # It sets up layout and widgets that are defined
    def run(self):
      self.show()  # Show the form
      app.exec_()  # and execute the app
    def connect_clicks(self,ds0):
      """Connect the different functions"""
      ds = dict()
      for d in ds0: ds[d] = get_failsafe(ds0[d],robust=True)
      for d in ds:
          bu = getattr(self,d) # label in the interface
          fun = ds[d] # function to call
#          self.connect(bu, SIGNAL("clicked()"),fun) # connect name to function
          bu.clicked.connect(fun) # connect name to function


def main():
    global form
    form = App()  # We set the form to be our ExampleApp (interface)
    return form


def add_numeric_validators(names):
  """Attach a numeric validator to the given QLineEdit widgets

  interface.ui ships no validators, so the fields accept anything; a locale
  decimal comma or a stray unit used to become a silent zero.
  """
  from PyQt5.QtGui import QDoubleValidator
  from PyQt5.QtCore import QLocale
  val = QDoubleValidator()
  val.setNotation(QDoubleValidator.ScientificNotation)
  val.setLocale(QLocale(QLocale.C)) # a dot is the decimal separator
  for name in names:
    obj = getattr(form,name,None)
    if obj is None: continue # widget not in this interface
    try: obj.setValidator(val)
    except AttributeError: pass # not a QLineEdit


def get(name,string=False):
  try:
    obj = getattr(form,name) # get the object
  except AttributeError: # a genuinely missing widget keeps the old behaviour
    print(name,"not found, set to zero")
    return 0
  out = obj.text()
  print(name,out)
  if string: return out # return as string
  try:
    return float(out) # return as float
  except (TypeError,ValueError):
    # do not silently zero a parameter: that changes the physics with no trace
    raise ValueError("The field '%s' does not contain a valid number: '%s'"
                     %(name,out))



def getbox(name):
  try:
    obj = getattr(form,name) # get the object
    return str(obj.currentText()) # return the text
  except:
    print(name,"not found, set to empty string")
    return 0



def modify(name,text):
  obj = getattr(form,name) # get the object
  out = obj.setText(str(text))
  app.processEvents() # update the interface


def set_value(name,text):
  obj = getattr(form,name) # get the object
  out = obj.setText(str(text))
  app.processEvents() # update the interface


def is_checked(name):
  obj = getattr(form,name) # get the object
  return obj.isChecked()



def set_image(name,path):
  """Set a certain image"""
  label = getattr(form,name) # get the object
  pixmap = QPixmap(path)
  label.setPixmap(pixmap)
  label.show()


def set_logo(name,path):
  """Set a certain logo"""
  set_image(name,path)
  



def connect_signals(ds):
  for d in ds: # loop over names
    form.connect(self.pb, SIGNAL("clicked()"),self.button_click)



if __name__ == '__main__':  # if we're running file directly and not importing it
    main()  # run the main function



